### ISSUE TITLE
Adding 10^ and log10 to fn_set

### ISSUE THREAD

**Issue by AmeliaFord353** [DeaglanBartlett/ESR#16]
A request to have additional operators available in basis functions of "10^" and "log10" for ESR function generation.

**Comment by DeaglanBartlett** [comment]
In f28246d2bba8091c6c0e26b8b9d8f48c99dbb33c the function set "base10_maths" has been added. The operators required (log10 and tenexp = 10^) have been defined in https://github.com/DeaglanBartlett/ESR/blob/5e1f2369e278dd9f85e9c572846c622e2890453d/esr/fitting/sympy_symbols.py alongside their names, so the code can recognise the functions
