### ISSUE TITLE
Reducing text output while ESR operates

### ISSUE THREAD

**Issue by AmeliaFord353** [DeaglanBartlett/ESR#19]
When running at high complexities, ESR produces a lot of text for each function as it goes through the process of generating and fitting them. It means that in order to view the final table produced, the screen has to race through pages and pages of text to reach it.
With the recent problems with Glamdring being overwhelmed by large IO files, I was thinking it might be worth cutting down on ESR's output to screen?

**Comment by DeaglanBartlett** [comment]
In 4d991e38ef62cadf87a6ce4a5deb80ce2d9b38c9, the number of print statements in the generation and fitting stages has been reduced. For the latter, we introduce an argument `print_frequency` to all the fitting routines which controls the frequency at which the status of the run is printed, i.e.

https://github.com/DeaglanBartlett/ESR/blob/4d991e38ef62cadf87a6ce4a5deb80ce2d9b38c9/esr/fitting/test_all.py#L342-L343

Is this a sufficient reduction in verbosity or are there other print statements which you think are redundant?

**Comment by AmeliaFord353** [comment]
Thank you - output text has been sufficiently reduced: you can still determine how the program is progressing as it operates, and the size of output is not unnecessarily large.
